"""fix7

Revision ID: 34ac76315537
Revises: f1e213c053f5
Create Date: 2024-04-02 16:27:23.320193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '34ac76315537'
down_revision: Union[str, None] = 'f1e213c053f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labeltasklink')
    op.add_column('task', sa.Column('label_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'label', ['label_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'label_id')
    op.create_table('labeltasklink',
    sa.Column('label_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], name='labeltasklink_label_id_fkey'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name='labeltasklink_task_id_fkey'),
    sa.PrimaryKeyConstraint('label_id', 'task_id', name='labeltasklink_pkey')
    )
    # ### end Alembic commands ###
