"""fix8

Revision ID: 4f99ac360c87
Revises: 34ac76315537
Create Date: 2024-04-02 16:45:52.454559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4f99ac360c87'
down_revision: Union[str, None] = '34ac76315537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('time_spent', sa.Float(), nullable=True))
    op.add_column('task', sa.Column('done_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'done_date')
    op.drop_column('task', 'time_spent')
    # ### end Alembic commands ###
